WITH trip_metrics_denominator AS (
    SELECT tripstatus,
           partnercountryid,
           partnernetworkid,
           overallbucketid,
           roamertype,
           overallbucketidexcludingsor,
           regbucketid,
           regsuccessratiobucketid,
           reglatencybucketid,
           regbucketidexcludingsor,
           regsuccessratiobucketidexcludingsor,
           reglatencybucketidexcludingsor,
           callbucketid3g,
           callccrbucketid3g,
           callnerbucketid3g,
           callpddbucketid3g,
           callbucketidvolte,
           callnerbucketidvolte,
           callccrbucketidvolte,
           callpddbucketidvolte,
           callbucketid5g,
           callnerbucketid5g,
           callccrbucketid5g,
           callpddbucketid5g,
           callbucketid,
           callnerbucketid,
           callccrbucketid,
           callpddbucketid,
           mosmsbucketid3g,
           mosmssuccessratiobucketid3g,
           mosmslatencybucketid3g,
           mosmsbucketidvolte,
           mosmssuccessratiobucketidvolte,
           mosmslatencybucketidvolte,
           mosmsbucketid5g,
           mosmssuccessratiobucketid5g,
           mosmslatencybucketid5g,
           mosmsbucketid,
           mosmssuccessratiobucketid,
           mosmslatencybucketid,
           databucketid3g,
           datasuccessratiobucketid3g,
           datacutoffratiobucketid3g,
           datathroughputbucketid3g,
           databucketid4g,
           datasuccessratiobucketid4g,
           datacutoffratiobucketid4g,
           datathroughputbucketid4g,
           databucketid5g,
           datasuccessratiobucketid5g,
           datacutoffratiobucketid5g,
           datathroughputbucketid5g,
           databucketid,
           datasuccessratiobucketid,
           datacutoffratiobucketid,
           datathroughputbucketid
    FROM trip_metrics_closed
    WHERE roamertype = 2
      AND tripstatus IN (2, 3)
      AND partnercountryid = 351
      AND bintime = 1756598400
      AND triptype = 'N'
)
SELECT partnercountryid,
       partnernetworkid,
       tripstatus,
       SUM(CASE WHEN roamertype = 2 AND overallbucketid <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_overall_sordisabled_denominator,
       SUM(CASE WHEN roamertype = 2 AND overallbucketidexcludingsor <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_overall_sorenabled_denominator,
       SUM(CASE WHEN roamertype = 2 AND regbucketid <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_registrationoverall_sordisabled_denominator,
       SUM(CASE WHEN roamertype = 2 AND regbucketidexcludingsor <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_registrationoverall_sexcludingordisabled_denominator,
       SUM(CASE WHEN roamertype = 2 AND regsuccessratiobucketid <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_registrationlatencyratio_sordisabled_denominator,
       SUM(CASE WHEN roamertype = 2 AND regsuccessratiobucketidexcludingsor <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_registrationoverall_sorenabled_denominator,
       SUM(CASE WHEN roamertype = 2 AND reglatencybucketid <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_registrationsuccessratio_sordisabled_denominator,
       SUM(CASE WHEN roamertype = 2 AND reglatencybucketidexcludingsor <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_registrationlatencyratio_sorenabled_denominator,
       SUM(CASE WHEN roamertype = 2 AND callbucketid3g <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_overallcall3g_denominator,
       SUM(CASE WHEN roamertype = 2 AND callccrbucketid3g <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_callccr3g_denominator,
       SUM(CASE WHEN roamertype = 2 AND callnerbucketid3g <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_callner3g_denominator,
       SUM(CASE WHEN roamertype = 2 AND callpddbucketid3g <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_callpdd3g_denominator,
       SUM(CASE WHEN roamertype = 2 AND callbucketidvolte <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_overallcallvolte_denominator,
       SUM(CASE WHEN roamertype = 2 AND callccrbucketidvolte <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_callccrvolte_denominator,
       SUM(CASE WHEN roamertype = 2 AND callnerbucketidvolte <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_callnervolte_denominator,
       SUM(CASE WHEN roamertype = 2 AND callpddbucketidvolte <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_callpddvolte_denominator,
       SUM(CASE WHEN roamertype = 2 AND callbucketid5g <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_overallcall5g_denominator,
       SUM(CASE WHEN roamertype = 2 AND callccrbucketid5g <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_callccr5g_denominator,
       SUM(CASE WHEN roamertype = 2 AND callnerbucketid5g <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_callner5g_denominator,
       SUM(CASE WHEN roamertype = 2 AND callpddbucketid5g <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_callpdd5g_denominator,
       SUM(CASE WHEN roamertype = 2 AND callbucketid <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_overallcall_denominator,
       SUM(CASE WHEN roamertype = 2 AND callccrbucketid <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_callccr_denominator,
       SUM(CASE WHEN roamertype = 2 AND callnerbucketid <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_callner_denominator,
       SUM(CASE WHEN roamertype = 2 AND callpddbucketid <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_callpdd_denominator,
       SUM(CASE WHEN roamertype = 2 AND databucketid3g <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_overalldata3g_denominator,
       SUM(CASE WHEN roamertype = 2 AND datasuccessratiobucketid3g <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_datasuccessratio3g_denominator,
       SUM(CASE WHEN roamertype = 2 AND datacutoffratiobucketid3g <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_datacutoffratio3g_denominator,
       SUM(CASE WHEN roamertype = 2 AND datathroughputbucketid3g <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_datathroughput3g_denominator,
       SUM(CASE WHEN roamertype = 2 AND databucketid4g <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_overalldata4g_denominator,
       SUM(CASE WHEN roamertype = 2 AND datasuccessratiobucketid4g <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_datasuccessratio4g_denominator,
       SUM(CASE WHEN roamertype = 2 AND datacutoffratiobucketid4g <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_datacutoffratio4g_denominator,
       SUM(CASE WHEN roamertype = 2 AND datathroughputbucketid4g <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_datathroughput4g_denominator,
       SUM(CASE WHEN roamertype = 2 AND databucketid5g <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_overalldata5g_denominator,
       SUM(CASE WHEN roamertype = 2 AND datasuccessratiobucketid5g <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_datasuccessratio5g_denominator,
       SUM(CASE WHEN roamertype = 2 AND datacutoffratiobucketid5g <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_datacutoffratio5g_denominator,
       SUM(CASE WHEN roamertype = 2 AND datathroughputbucketid5g <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_datathroughput5g_denominator,
       SUM(CASE WHEN roamertype = 2 AND databucketid <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_overalldata_denominator,
       SUM(CASE WHEN roamertype = 2 AND datasuccessratiobucketid <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_datasuccessratio_denominator,
       SUM(CASE WHEN roamertype = 2 AND datacutoffratiobucketid <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_datacutoffratio_denominator,
       SUM(CASE WHEN roamertype = 2 AND datathroughputbucketid <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_datathroughput_denominator,
       SUM(CASE WHEN roamertype = 2 AND mosmsbucketid3g <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_mosmsbucketid3g_sordisabled_denominator,
       SUM(CASE WHEN roamertype = 2 AND mosmssuccessratiobucketid3g <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_mosmssuccessratiobucketid3g_sordisabled_denominator,
       SUM(CASE WHEN roamertype = 2 AND mosmslatencybucketid3g <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_mosmslatencybucketid3g_sordisabled_denominator,
       SUM(CASE WHEN roamertype = 2 AND mosmsbucketidvolte <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_mosmsbucketidvolte_sordisabled_denominator,
       SUM(CASE WHEN roamertype = 2 AND mosmssuccessratiobucketidvolte <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_mosmssuccessratiobucketidvolte_sordisabled_denominator,
       SUM(CASE WHEN roamertype = 2 AND mosmslatencybucketidvolte <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_mosmslatencybucketidvolte_sordisabled_denominator,
       SUM(CASE WHEN roamertype = 2 AND mosmsbucketid5g <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_mosmsbucketid5g_sordisabled_denominator,
       SUM(CASE WHEN roamertype = 2 AND mosmssuccessratiobucketid5g <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_mosmssuccessratiobucketid5g_sordisabled_denominator,
       SUM(CASE WHEN roamertype = 2 AND mosmslatencybucketid5g <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_mosmslatencybucketid5g_sordisabled_denominator,
       SUM(CASE WHEN roamertype = 2 AND mosmsbucketid <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_mosmsbucketid_sordisabled_denominator,
       SUM(CASE WHEN roamertype = 2 AND mosmssuccessratiobucketid <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_mosmssuccessratiobucketid_sordisabled_denominator,
       SUM(CASE WHEN roamertype = 2 AND mosmslatencybucketid <> 0 THEN 1 ELSE 0 END) AS trip_metrics_closed_mosmslatencybucketid_sordisabled_denominator
FROM trip_metrics_denominator
GROUP BY partnercountryid, partnernetworkid, tripstatus;

